coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - 'packages/*/tests/**'
  - 'packages/shared/views/adapter.js'
  - 'packages/*/shared/**'
