/**
 * build-schemas.js — Composes the published per-platform JSON Schemas from a
 * layered chain of sources: a platform-agnostic base, optional family layers,
 * and a per-surface leaf delta.
 *
 * Sources of truth (edit these):
 *   schemas/shared.schema.json         — the platform-AGNOSTIC base: the
 *                                        top-level envelope (project +
 *                                        recordings) and every cross-platform
 *                                        $def (project, recording, step, the
 *                                        shared action types, element,
 *                                        modifiers, uuidv7, iso8601, context_id,
 *                                        metadata). No platform-specific fields
 *                                        or wording.
 *   schemas/desktop.shared.schema.json — the desktop-FAMILY layer shared by all
 *                                        desktop surfaces (Windows, future
 *                                        Linux): native capture_mode,
 *                                        window_rect(+_or_null), the desktop-only
 *                                        action_file_dialog, the desktop `action`
 *                                        oneOf, and the window_rect
 *                                        actionContextProperty directive.
 *   schemas/<surface>.delta.json       — the per-surface LEAF: identity only by
 *                                        default (title, version, description,
 *                                        $id) plus anything genuinely unique to
 *                                        that one surface. The extension leaf
 *                                        also carries its browser-only defs
 *                                        (frame_src, dom capture_mode,
 *                                        navigate/file_upload, its `action`
 *                                        oneOf) since the extension has no family
 *                                        layer.
 *
 * Layer chains are declared in PLATFORMS below (base first, leaf last). Later
 * layers override earlier ones key-by-key, so a family or leaf can add or
 * replace any $def from the base.
 *
 * Build output (DO NOT hand-edit — regenerated by this script, committed under
 * schemas/dist/ ONLY by the release pipeline so the published artifact tracks
 * the latest *release*, not every commit on main. Between releases dist/
 * intentionally lags the source layers. The dist/ dir contains ONLY publishable
 * platform schemas — keeping it separate from the source layers in schemas/ is
 * what makes filename-based discovery of "real" platform schemas unambiguous):
 *   schemas/dist/extension.schema.json
 *   schemas/dist/desktop-windows.schema.json
 *
 * IMPORTANT: tests and sync-shared must NOT read schemas/dist/ — it can be stale
 * relative to a PR's schema changes. They compose from the source layers
 * in-memory via composePlatform() (exported below). dist/ is for human review
 * and external consumers of the released contract only.
 *
 * The per-action context property (extension → frame_src, desktop →
 * window_rect) is declared once per chain via `actionContextProperty` (the
 * last layer that sets it wins) and the composer injects it into EVERY action
 * def. That is why no layer repeats the property on individual action defs.
 *
 * The composed output is formatted with the repo Prettier config so the
 * committed dist/ stays lint-clean.
 *
 * Usage:
 *   node scripts/build-schemas.js            # (re)write schemas/dist/ (release pipeline)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const ROOT = resolve(import.meta.dirname, '..');
const SCHEMAS_DIR = join(ROOT, 'schemas');
const DIST_DIR = join(SCHEMAS_DIR, 'dist');

// Each published schema is composed from an ordered layer chain: the
// platform-agnostic base first, then any family layer(s), then the per-surface
// leaf. Add a new desktop surface (e.g. Linux, #84) by giving it a leaf delta
// and the same [shared, desktop.shared, <leaf>] chain.
export const PLATFORMS = {
  extension: ['shared.schema.json', 'extension.delta.json'],
  'desktop-windows': [
    'shared.schema.json',
    'desktop.shared.schema.json',
    'desktop-windows.delta.json',
  ],
};

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

/**
 * Compose an ordered chain of schema layers into a full platform schema.
 *
 * Layers are merged base-first: `$defs` are combined key-by-key with later
 * layers overriding earlier ones; the structural envelope (type / required /
 * additionalProperties / properties) is taken from whichever layer defines it
 * (the base); identity metadata ($id / title / version / description) is taken
 * from the last layer that provides it (the leaf); and the per-action context
 * property is the last `actionContextProperty` set in the chain.
 *
 * @param {object[]} layers - parsed schema layers, base first, leaf last
 * @returns {object} the composed full schema
 */
export function compose(layers) {
  let mergedDefs = {};
  let actionContextProperty = null;
  let envelope = {};
  const meta = {};
  let $schema;

  for (const layer of layers) {
    const { $defs, actionContextProperty: acp, $schema: layerSchema, ...rest } = layer;

    if (layerSchema) $schema = layerSchema;
    if ($defs) mergedDefs = { ...mergedDefs, ...$defs };
    if (acp) actionContextProperty = acp;

    // Structural envelope — carried by the base. Captured when present.
    if (rest.type) {
      envelope = {
        type: rest.type,
        required: rest.required,
        additionalProperties: rest.additionalProperties,
        properties: rest.properties,
      };
    }

    // Identity metadata — last layer to set each key wins (the leaf).
    for (const key of ['$id', 'title', 'version', 'description']) {
      if (rest[key] !== undefined) meta[key] = rest[key];
    }
  }

  // Deep-clone so per-action injection never mutates a source layer and building
  // one platform cannot leak into another.
  mergedDefs = structuredClone(mergedDefs);

  // Inject the per-action context property (frame_src / window_rect) into EVERY
  // action def. Appended last, after the def's own properties. This is why no
  // layer repeats the property on individual action defs — the composer is the
  // single place that applies it.
  if (actionContextProperty) {
    for (const [name, def] of Object.entries(mergedDefs)) {
      // `action` is the oneOf wrapper, not a concrete action — skip it.
      if (name.startsWith('action_') && def.properties) {
        def.properties[actionContextProperty.name] = actionContextProperty.schema;
      }
    }
  }

  // Fixed key order: $schema + identity metadata, structural envelope, $defs.
  return {
    $schema,
    $id: meta.$id,
    title: meta.title,
    version: meta.version,
    description: meta.description,
    type: envelope.type,
    required: envelope.required,
    additionalProperties: envelope.additionalProperties,
    properties: envelope.properties,
    $defs: mergedDefs,
  };
}

/**
 * Compose a platform's published schema from its SOURCE LAYERS, in-memory.
 *
 * This is the canonical way for tests and sync-shared to obtain a platform
 * schema: it reflects the current working-tree source layers, so it picks up
 * schema changes in a PR before they have been released into schemas/dist/.
 * Never read schemas/dist/ for validation — it can be stale relative to source.
 *
 * @param {string} platform - a key of PLATFORMS (e.g. "extension")
 * @returns {object} the composed full schema
 */
export function composePlatform(platform) {
  const chain = PLATFORMS[platform];
  if (!chain) {
    throw new Error(`Unknown platform "${platform}". Known: ${Object.keys(PLATFORMS).join(', ')}`);
  }
  return compose(chain.map((file) => readJson(join(SCHEMAS_DIR, file))));
}

async function format(obj) {
  const config = (await prettier.resolveConfig(join(SCHEMAS_DIR, 'x.json'))) || {};
  // Pre-indent with 2 spaces so every object opens with a newline after `{`.
  // Prettier preserves that expansion for JSON objects (a bare JSON.stringify
  // with no spacing would let Prettier collapse short objects onto one line).
  return prettier.format(JSON.stringify(obj, null, 2), { ...config, parser: 'json' });
}

/**
 * Write each platform's composed schema to schemas/dist/. Invoked by the
 * release pipeline (and locally when refreshing the published artifact).
 */
async function build() {
  mkdirSync(DIST_DIR, { recursive: true });

  for (const platform of Object.keys(PLATFORMS)) {
    const composed = await format(composePlatform(platform));
    writeFileSync(join(DIST_DIR, `${platform}.schema.json`), composed, 'utf8');
    console.log(`✓ composed schemas/dist/${platform}.schema.json`);
  }
}

// Only run the build when invoked directly (`node scripts/build-schemas.js`),
// not when imported by a test/consumer for the exported compose helpers.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  build();
}
